[build]
  command = "quasar build -m ssr"
  publish = "dist/ssr/www"

[build.environment]
  NODE_VERSION = "22"

# === PROBLEMA IDENTIFICADO: Functions config incorreta ===
# O problema está na configuração de functions que está conflitando

# === REDIRECTS CORRIGIDOS PARA SSR + PWA ===

# 1. Assets estáticos PRIMEIRO (alta prioridade)
[[redirects]]
  from = "/icons/*"
  to = "/icons/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/fonts/*"
  to = "/fonts/:splat"
  status = 200

[[redirects]]
  from = "/statics/*"
  to = "/statics/:splat"
  status = 200

# 2. PWA files (crítico para funcionamento)
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# 3. Página offline (deve ser servida diretamente)
[[redirects]]
  from = "/offline.html"
  to = "/offline.html"
  status = 200

# 4. API externa (não deve passar pelo SSR)
[[redirects]]
  from = "/api/*"
  to = "https://polished-snowflake-9723.fly.dev/api/:splat"
  status = 200

# 5. Health check
[[redirects]]
  from = "/health"
  to = "/health"
  status = 200

# === CORREÇÃO PRINCIPAL: SPA Fallback para todas as rotas ===
# Em vez de functions render, usa fallback SPA padrão
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# === HEADERS OTIMIZADOS ===
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para JS (longo)
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para CSS (longo)
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para fontes (longo)
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para ícones (médio)
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# PWA files (sem cache para updates)
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache para imagens (médio)
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# HTML pages (cache curto para updates frequentes)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=600"

# === CONFIGURAÇÃO DE IMAGENS EXTERNA ===
[images]
  remote_images = ["https://abaete-fest.s3.amazonaws.com/*"]